server {
    listen 80;
    server_name localhost;
    
    # Увеличиваем лимит данных до 50 мегабайт
    client_max_body_size 50M;
    
    # 1. Отдаем статику (твой HTML, CSS, JS)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Проксируем API-запросы на бэкенд
    location /api/ {
        # 'backend' - это имя сервиса из твоего docker-compose.yml
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
